server:
  port: 8082
spring:
  application:
    name: StoreManagementSystem        
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true